#!/bin/bash
# tunnel-vm-tune.sh — Network optimization for tunnel VMs
# Usage: sudo bash tunnel-vm-tune.sh
# Rollback: sudo bash /root/tunnel-vm-tune-rollback.sh   (generated on every run)
#
# Tailored for reverse-tunnel engines (e.g. Backhaul/tunnel-manager) that hold
# a large number of concurrent connections: widens the ephemeral port range
# and conntrack table instead of narrowing them, and explicitly reserves the
# ports already in LISTEN state so the ephemeral range never collides with a
# tunnel's own bind port. Re-run after adding a new tunnel/port so the
# reserved-port list stays current.

set -uo pipefail

SYSCTL_CONF=/etc/sysctl.d/99-tunnel-vm.conf
BBR_MODULE_CONF=/etc/modules-load.d/tunnel-vm-bbr.conf
ROLLBACK_SCRIPT=/root/tunnel-vm-tune-rollback.sh
LIMITS_TAG="tunnel-vm-tune"

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: this script must be run as root."
    exit 1
fi

echo "=== [1/6] Backing up current settings ==="
BACKUP_FILE="/root/sysctl-backup-$(date +%F-%H%M%S)-$$.txt"
sysctl -a > "$BACKUP_FILE" 2>/dev/null
cp -n /etc/security/limits.conf /root/limits.conf.bak 2>/dev/null || true
echo "Backup saved to $BACKUP_FILE"

cat > "$ROLLBACK_SCRIPT" <<EOF
#!/bin/bash
# Generated by tunnel-vm-tune.sh on $(date -Iseconds)
set -uo pipefail
if [ "\$(id -u)" -ne 0 ]; then
    echo "Error: run as root."
    exit 1
fi
rm -f $SYSCTL_CONF $BBR_MODULE_CONF
sed -i "/# $LIMITS_TAG/,+4d" /etc/security/limits.conf
rm -f /etc/systemd/system.conf.d/99-tunnel-vm-nofile.conf
systemctl daemon-reexec 2>/dev/null || true
sysctl --system >/dev/null
echo "Rolled back. Pre-change values were recorded in: $BACKUP_FILE"
EOF
chmod +x "$ROLLBACK_SCRIPT"
echo "Rollback script written to $ROLLBACK_SCRIPT"

echo "=== [2/6] Checking BBR support ==="
BBR_OK=0
if ! sysctl net.ipv4.tcp_available_congestion_control 2>/dev/null | grep -q bbr; then
    modprobe tcp_bbr 2>/dev/null || true
fi
if sysctl net.ipv4.tcp_available_congestion_control 2>/dev/null | grep -q bbr; then
    echo "BBR is available (OK)"
    BBR_OK=1
    mkdir -p /etc/modules-load.d
    grep -qs '^tcp_bbr$' "$BBR_MODULE_CONF" 2>/dev/null || echo tcp_bbr > "$BBR_MODULE_CONF"
else
    echo "Warning: BBR not available in this kernel/container — applying buffer tuning only"
fi

echo "=== [3/6] Checking connection tracking (conntrack) support ==="
CONNTRACK_OK=0
[ -f /proc/sys/net/netfilter/nf_conntrack_max ] || modprobe nf_conntrack 2>/dev/null || true
if [ -f /proc/sys/net/netfilter/nf_conntrack_max ]; then
    CONNTRACK_OK=1
    if [ -w /sys/module/nf_conntrack/parameters/hashsize ]; then
        echo 65536 > /sys/module/nf_conntrack/parameters/hashsize 2>/dev/null || true
    fi
    echo "conntrack is available (OK)"
else
    echo "conntrack not available in this kernel/container — skipping conntrack tuning"
fi

echo "=== [4/6] Detecting ports already in LISTEN state ==="
# Reserve them out of the ephemeral range (net.ipv4.ip_local_reserved_ports) so
# the wide port range below never gets handed out as an outgoing ephemeral
# port that collides with a tunnel's own bind port.
RESERVED_PORTS=$( { ss -Htln 2>/dev/null; ss -Huln 2>/dev/null; } \
    | awk '{print $4}' | grep -oE '[0-9]+$' | sort -un | paste -sd, - )
if [ -n "$RESERVED_PORTS" ]; then
    echo "Reserving currently-listening ports from the ephemeral range: $RESERVED_PORTS"
else
    echo "No listening ports detected to reserve"
fi

echo "=== [5/6] Applying sysctl settings ==="
cat > "$SYSCTL_CONF" << 'EOF'
# --- Network buffers ---
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.rmem_default = 1048576
net.core.wmem_default = 1048576
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 65536 33554432
net.core.netdev_max_backlog = 30000
# --- Connection capacity (wide on purpose — this is for engines that hold
# many thousands of concurrent tunnel connections; see ip_local_reserved_ports
# below for how the tunnel's own bind port is kept safe) ---
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
# --- Misc improvements ---
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_no_metrics_save = 1
# --- Dead-peer detection for long-lived tunnel connections ---
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6
EOF

if [ -n "$RESERVED_PORTS" ]; then
    echo "net.ipv4.ip_local_reserved_ports = $RESERVED_PORTS" >> "$SYSCTL_CONF"
fi

if [ "$CONNTRACK_OK" = "1" ]; then
cat >> "$SYSCTL_CONF" << 'EOF'
# --- Connection tracking ---
net.netfilter.nf_conntrack_max = 262144
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
EOF
fi

if [ "$BBR_OK" = "1" ]; then
cat >> "$SYSCTL_CONF" << 'EOF'
# --- BBR ---
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF
fi

# -e: ignore keys the current kernel/namespace doesn't expose (common in
# OpenVZ/LXC guests) instead of aborting the whole apply on the first miss.
sysctl -e -p "$SYSCTL_CONF" > /dev/null
echo "Sysctl settings applied (OK)"

if [ "$BBR_OK" = "1" ]; then
    echo "Applying fq qdisc to active interfaces (default_qdisc only affects newly-created ones)"
    for iface in $(ip -o link show up 2>/dev/null | awk -F': ' '{print $2}' | grep -v '^lo$'); do
        if tc qdisc replace dev "$iface" root fq 2>/dev/null; then
            echo "  $iface -> fq (OK)"
        else
            echo "  $iface -> could not set fq (non-fatal)"
        fi
    done
fi

echo "=== [6/6] Raising open-file limits ==="
if ! grep -q "$LIMITS_TAG" /etc/security/limits.conf; then
cat >> /etc/security/limits.conf << EOF
# $LIMITS_TAG
* soft nofile 1048576
* hard nofile 1048576
root soft nofile 1048576
root hard nofile 1048576
EOF
fi
echo "limits.conf updated (OK)"

# limits.conf is only read by PAM login sessions — systemd services (which is
# how tunnel-manager runs each engine) ignore it entirely. tunnel-manager's
# own Backhaul units already set LimitNOFILE=1048576 directly, but this
# raises the system-wide default so any other systemd-managed service on the
# box benefits too, without editing individual units.
mkdir -p /etc/systemd/system.conf.d
cat > /etc/systemd/system.conf.d/99-tunnel-vm-nofile.conf << 'EOF'
[Manager]
DefaultLimitNOFILE=1048576
EOF
systemctl daemon-reexec 2>/dev/null || true
echo "systemd DefaultLimitNOFILE raised (OK)"

echo "=== Final verification ==="
echo "--------------------------------"
echo "Congestion Control: $(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo n/a)"
echo "Qdisc:              $(sysctl -n net.core.default_qdisc 2>/dev/null || echo n/a)"
echo "Backlog:            $(sysctl -n net.core.netdev_max_backlog)"
echo "somaxconn:          $(sysctl -n net.core.somaxconn)"
if [ "$CONNTRACK_OK" = "1" ]; then
    echo "conntrack max:       $(sysctl -n net.netfilter.nf_conntrack_max 2>/dev/null || echo n/a)"
fi
if [ -n "$RESERVED_PORTS" ]; then
    echo "Reserved ports:      $RESERVED_PORTS"
fi
echo "--------------------------------"
echo "Done. Sysctl settings are active now. Rollback: sudo bash $ROLLBACK_SCRIPT"
echo
echo "Backhaul-specific notes (not applied by this script — set in tunnel-manager's own config):"
echo "  - so_rcvbuf/so_sndbuf in your backhaul TOML are capped by net.core.rmem_max/wmem_max."
echo "    They were just raised to 64MB, so values like so_rcvbuf=4194304 will now actually take effect."
echo "  - If you use TUN mode with ipx encapsulation (gre/ipip/icmp/...), set 'mss' explicitly"
echo "    (e.g. 1200-1360) in that tunnel's config to avoid black-hole fragmentation from the"
echo "    encapsulation overhead — tcp_mtu_probing alone won't fully cover an encapsulated path."
echo "  - Reserved-port detection above is a snapshot: re-run this script after configuring a new"
echo "    tunnel/port so it stays excluded from the ephemeral range."
